# Generated by Django 3.0.3 on 2020-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votelist_myname'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelist',
            name='votenum',
            field=models.IntegerField(default=0),
        ),
    ]
